 references:
 # * http://www.objc.io/issue-6/travis-ci.html
 # * https://github.com/supermarin/xcpretty#usage

 language: swift
 rvm: 2.2.2
 before_install:
 - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
 script:
 - set -o pipefail
 #- xctool test -workspace Example/QExpandableTableView.xcworkspace/ -scheme QExpandableTableView-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
 #- pod lib lint
